FROM ubuntu:22.04

WORKDIR /usr/src

# COPY server_setup.sh .

# RUN chmod +x server_setup.sh && ./server_setup.sh

RUN apt update && apt install -y libvulkan1 libgl1 libglib2.0-0 wget

# Install CUDA toolkit 11.8
RUN wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run

RUN apt update && apt install -y tar gzip build-essential perl

RUN sh cuda_11.8.0_520.61.05_linux.run --silent --toolkit

# Install NVIDIA driver 530
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:graphics-drivers/ppa

RUN apt update && apt install -y nvidia-driver-515

RUN wget https://github.com/Juice-Labs/Juice-Labs/releases/latest/download/JuiceServer-linux.tar.gz

RUN mkdir JuiceServer && cd JuiceServer && tar -xf ../JuiceServer-linux.tar.gz

CMD ["/usr/src/JuiceServer/agent"]