FROM python:3.10

# ENV MODEL='orca-mini-3b-gguf2-q4_0.gguf'

WORKDIR /usr/src

RUN apt update && apt install -y wget git libvulkan1 libgl1 libglib2.0-0

RUN wget https://github.com/Juice-Labs/Juice-Labs/releases/latest/download/JuiceClient-linux.tar.gz

WORKDIR /usr/src/JuiceClient

RUN tar -xf ../JuiceClient-linux.tar.gz

WORKDIR /usr/src/JuiceClient/app

# RUN wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh
COPY webui.sh .

# COPY requirements.txt .
# COPY chatty.py .

# RUN pip install -r requirements.txt

# COPY download_model.py .

# RUN python download_model.py

COPY juice.cfg /usr/src/JuiceClient/

RUN chmod +x webui.sh

CMD [ "/usr/src/JuiceClient/juicify", "/usr/src/JuiceClient/app/webui.sh" ]

