FROM ubuntu:jammy

RUN \
    apt update && \
    apt install -y libvulkan1 libgl1 libglib2.0-0 wget

RUN \
    wget https://github.com/Juice-Labs/Juice-Labs/releases/latest/download/JuiceClient-linux.tar.gz && \
    mkdir JuiceClient && \
    tar -xf ../JuiceClient-linux.tar.gz -C JuiceClient

RUN \
    apt install -y python3 python3-pip

WORKDIR /JuiceClient

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY llms/yarn-llama-2-13b-64k.Q4_K_M.gguf /usr/src/JuiceClient/app/
COPY chatty.py .

ENV JUICESERVER 127.0.0.1:43210 

CMD ./juicify --address ${JUICESERVER} python3 -u chatty.py